#pragma once

#include <cstdint>

namespace chx::sql::mysql {
struct capabilities_flags {
    static constexpr std::uint32_t
        CLIENT_LONG_PASSWORD = 1,
        CLIENT_FOUND_ROWS = 2, CLIENT_LONG_FLAG = 4, CLIENT_CONNECT_WITH_DB = 8,
        CLIENT_NO_SCHEMA = 16, CLIENT_COMPRESS = 32, CLIENT_ODBC = 64,
        CLIENT_LOCAL_FILES = 128, CLIENT_IGNORE_SPACE = 256,
        CLIENT_PROTOCOL_41 = 512, CLIENT_INTERACTIVE = 1024, CLIENT_SSL = 2048,
        CLIENT_IGNORE_SIGPIPE = 4096, CLIENT_TRANSACTIONS = 8192,
        CLIENT_RESERVED = 16384, CLIENT_RESERVED2 = 32768,
        CLIENT_MULTI_STATEMENTS = (1UL << 16),
        CLIENT_MULTI_RESULTS = (1UL << 17),
        CLIENT_PS_MULTI_RESULTS = (1UL << 18), CLIENT_PLUGIN_AUTH = (1UL << 19),
        CLIENT_CONNECT_ATTRS = (1UL << 20),
        CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA = (1UL << 21),
        CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS = (1UL << 22),
        CLIENT_SESSION_TRACK = (1UL << 23), CLIENT_DEPRECATE_EOF = (1UL << 24),
        CLIENT_OPTIONAL_RESULTSET_METADATA = (1UL << 25),
        CLIENT_ZSTD_COMPRESSION_ALGORITHM = (1UL << 26),
        CLIENT_QUERY_ATTRIBUTES = (1UL << 27),
        MULTI_FACTOR_AUTHENTICATION = (1UL << 28),
        CLIENT_CAPABILITY_EXTENSION = (1UL << 29),
        CLIENT_SSL_VERIFY_SERVER_CERT = (1UL << 30),
        CLIENT_REMEMBER_OPTIONS = (1UL << 31);
};
}  // namespace chx::sql::mysql